import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryColumn,
} from 'typeorm';

/**
 * The `refresh_tokens` table: one row per token. Rows of one session share
 * `family_id`. `user_id` has no foreign key, because users belong to another
 * domain, which this one knows only by id.
 */
@Entity('refresh_tokens')
export class RefreshTokenRecord {
  /** Generated by the codec, because the client gets it inside the token. */
  @PrimaryColumn('uuid')
  id!: string;

  @Index()
  @Column({ name: 'user_id', type: 'uuid' })
  userId!: string;

  @Index()
  @Column({ name: 'family_id', type: 'uuid' })
  familyId!: string;

  /** SHA-256 of the secret part. The secret itself is never stored. */
  @Column({ name: 'token_hash' })
  tokenHash!: string;

  @Column({ name: 'expires_at', type: 'timestamptz' })
  expiresAt!: Date;

  /** Set when the token was exchanged for a new one. */
  @Column({ name: 'used_at', type: 'timestamptz', nullable: true })
  usedAt!: Date | null;

  /** Set when the session was ended: logout or a reused token. */
  @Column({ name: 'revoked_at', type: 'timestamptz', nullable: true })
  revokedAt!: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;
}
