/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Checks email and password and sets both token cookies. */
    post: operations['LoginController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchanges the refresh token cookie for new tokens. Permissions are read
     *     from the database again, so a change applies from here on.
     */
    post: operations['LoginController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ends the session and removes both cookies. */
    post: operations['LoginController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The logged in user. */
    get: operations['UsersController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** All users. Example of a route that needs a permission. */
    get: operations['UsersController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_live'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HelloDto: {
      message: string;
    };
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
    };
    UserDto: {
      id: string;
      email: string;
      /** @description Permission codes, for example `users:read`. */
      permissions: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HelloDto'];
        };
      };
    };
  };
  LoginController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description The body does not match LoginDto */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": [
           *         "email must be an email address",
           *         "password must not be empty",
           *         "password must be text"
           *       ],
           *       "error": "Bad Request",
           *       "statusCode": 400
           *     }
           */
          'application/json': unknown;
        };
      };
      /** @description Unknown email or wrong password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Invalid email or password",
           *       "error": "Unauthorized",
           *       "statusCode": 401
           *     }
           */
          'application/json': unknown;
        };
      };
      /** @description More than 5 attempts a minute from one address. Blocks for 15 minutes, Retry-After gives the seconds left */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "statusCode": 429,
           *       "message": "Too many attempts, try again later"
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  LoginController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description Missing, expired or reused refresh token. Both cookies are cleared */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Unauthorized",
           *       "statusCode": 401
           *     }
           */
          'application/json': unknown;
        };
      };
      /** @description More than 20 attempts a minute from one address. Blocks for 1 minute, Retry-After gives the seconds left */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "statusCode": 429,
           *       "message": "Too many attempts, try again later"
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  LoginController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
      /** @description Missing, expired or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Unauthorized",
           *       "statusCode": 401
           *     }
           */
          'application/json': unknown;
        };
      };
      /** @description The user was deleted after the token was issued */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Not Found",
           *       "statusCode": 404
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  UsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'][];
        };
      };
      /** @description Missing, expired or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Unauthorized",
           *       "statusCode": 401
           *     }
           */
          'application/json': unknown;
        };
      };
      /** @description The user lacks a permission: users:read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Forbidden",
           *       "statusCode": 403
           *     }
           */
          'application/json': unknown;
        };
      };
    };
  };
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example ok
             * @enum {string}
             */
            status?: 'ok' | 'degraded';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example error
             * @enum {string}
             */
            status?: 'error' | 'shutting_down';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example ok
             * @enum {string}
             */
            status?: 'ok' | 'degraded';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example error
             * @enum {string}
             */
            status?: 'error' | 'shutting_down';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
}
