/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchanges email and password for an access token. */
    post: operations['LoginController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The logged in user. */
    get: operations['UsersController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** All users. Example of a route that needs a permission. */
    get: operations['UsersController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_live'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HelloDto: {
      message: string;
    };
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
    };
    TokenDto: {
      /** @description Send it as `Authorization: Bearer <token>`. */
      accessToken: string;
      /** @description Seconds until the token expires. */
      expiresIn: number;
    };
    UserDto: {
      id: string;
      email: string;
      /** @description Permission codes, for example `users:read`. */
      permissions: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HelloDto'];
        };
      };
    };
  };
  LoginController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenDto'];
        };
      };
    };
  };
  UsersController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'];
        };
      };
    };
  };
  UsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDto'][];
        };
      };
    };
  };
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example ok
             * @enum {string}
             */
            status?: 'ok' | 'degraded';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example error
             * @enum {string}
             */
            status?: 'error' | 'shutting_down';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example ok
             * @enum {string}
             */
            status?: 'ok' | 'degraded';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example error
             * @enum {string}
             */
            status?: 'error' | 'shutting_down';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
}
