/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Checks email and password and sets both token cookies. */
    post: operations['LoginController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchanges the refresh token cookie for new tokens. Permissions are read
     *     from the database again, so a change applies from here on.
     */
    post: operations['LoginController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ends the session and removes both cookies. */
    post: operations['LoginController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The logged in user. */
    get: operations['UsersController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** All users. Example of a route that needs a permission. */
    get: operations['UsersController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_live'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HelloDto: {
      message: string;
    };
    LoginDto: {
      /** Format: email */
      email: string;
      password: string;
    };
    UserDto: {
      id: string;
      email: string;
      /** @description Permission codes, for example `users:read`. */
      permissions: string[];
    };
    /** @enum {string} */
    ResponseCode:
      | 'OK'
      | 'VALIDATION_ERROR'
      | 'AUTH_INVALID_CREDENTIALS'
      | 'AUTH_TOO_MANY_ATTEMPTS'
      | 'AUTH_UNAUTHENTICATED'
      | 'AUTH_REFRESH_REJECTED'
      | 'AUTH_FORBIDDEN'
      | 'ROUTE_NOT_FOUND'
      | 'UNEXPECTED_ERROR';
    /** @enum {string} */
    FieldCode:
      | 'REQUIRED'
      | 'UNKNOWN_FIELD'
      | 'INVALID_TYPE'
      | 'INVALID_EMAIL'
      | 'TOO_SHORT'
      | 'TOO_LONG'
      | 'LENGTH_OUT_OF_RANGE'
      | 'TOO_SMALL'
      | 'TOO_LARGE'
      | 'NOT_ALLOWED'
      | 'INVALID_VALUE';
    FieldError: {
      /** @example email */
      field: string;
      code: components['schemas']['FieldCode'];
      params?: {
        [key: string]: unknown;
      };
    };
    ErrorEnvelope: {
      /** @enum {string} */
      status: 'error';
      code: components['schemas']['ResponseCode'];
      params?: {
        [key: string]: unknown;
      };
      details?: components['schemas']['FieldError'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'success';
            code: components['schemas']['ResponseCode'];
            data: components['schemas']['HelloDto'];
          };
        };
      };
      /** @description `UNEXPECTED_ERROR`: An error nobody designed. A bug to fix, never returned on purpose */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "UNEXPECTED_ERROR"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  LoginController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'success';
            code: components['schemas']['ResponseCode'];
            data: components['schemas']['UserDto'];
          };
        };
      };
      /** @description `VALIDATION_ERROR`: The body does not match LoginDto */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "VALIDATION_ERROR"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `AUTH_INVALID_CREDENTIALS`: Unknown email or wrong password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "AUTH_INVALID_CREDENTIALS"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `AUTH_TOO_MANY_ATTEMPTS`: More than 5 attempts a minute from one address. Blocks for 15 minutes; `retryAfter` and the Retry-After header give the seconds left */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "AUTH_TOO_MANY_ATTEMPTS",
           *       "params": {
           *         "retryAfter": 900
           *       }
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `UNEXPECTED_ERROR`: An error nobody designed. A bug to fix, never returned on purpose */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "UNEXPECTED_ERROR"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  LoginController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'success';
            code: components['schemas']['ResponseCode'];
            data: components['schemas']['UserDto'];
          };
        };
      };
      /** @description `AUTH_REFRESH_REJECTED`: Missing, expired or reused refresh token. Both cookies are cleared */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "AUTH_REFRESH_REJECTED"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `AUTH_TOO_MANY_ATTEMPTS`: More than 20 attempts a minute from one address. Blocks for 1 minute */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "AUTH_TOO_MANY_ATTEMPTS",
           *       "params": {
           *         "retryAfter": 60
           *       }
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `UNEXPECTED_ERROR`: An error nobody designed. A bug to fix, never returned on purpose */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "UNEXPECTED_ERROR"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  LoginController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'success';
            code: components['schemas']['ResponseCode'];
            /** @enum {unknown|null} */
            data: null;
          };
        };
      };
      /** @description `UNEXPECTED_ERROR`: An error nobody designed. A bug to fix, never returned on purpose */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "UNEXPECTED_ERROR"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  UsersController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'success';
            code: components['schemas']['ResponseCode'];
            data: components['schemas']['UserDto'];
          };
        };
      };
      /** @description `AUTH_UNAUTHENTICATED`: Missing or expired access token, or the account no longer exists. Refresh the session and repeat */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "AUTH_UNAUTHENTICATED"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `UNEXPECTED_ERROR`: An error nobody designed. A bug to fix, never returned on purpose */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "UNEXPECTED_ERROR"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  UsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'success';
            code: components['schemas']['ResponseCode'];
            data: components['schemas']['UserDto'][];
          };
        };
      };
      /** @description `AUTH_UNAUTHENTICATED`: Missing or expired access token, or the account no longer exists. Refresh the session and repeat */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "AUTH_UNAUTHENTICATED"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `AUTH_FORBIDDEN`: The user lacks a permission: users:read */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "AUTH_FORBIDDEN"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description `UNEXPECTED_ERROR`: An error nobody designed. A bug to fix, never returned on purpose */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "status": "error",
           *       "code": "UNEXPECTED_ERROR"
           *     }
           */
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example ok
             * @enum {string}
             */
            status?: 'ok' | 'degraded';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example error
             * @enum {string}
             */
            status?: 'error' | 'shutting_down';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example ok
             * @enum {string}
             */
            status?: 'ok' | 'degraded';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example error
             * @enum {string}
             */
            status?: 'error' | 'shutting_down';
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "responseTime": 12
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect",
             *         "responseTime": 3005
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                /** @enum {string} */
                status: 'up' | 'degraded' | 'down';
                /** @description Time the health indicator took to respond, in ms */
                responseTime?: number;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
}
